vich_uploader:
    db_driver: orm

    mappings:
        posts:
            uri_prefix: /media/posts
            upload_destination: '%kernel.project_dir%/public/media/posts'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
